export interface SeedProvider {
  id: string;
  profile_id: string;
  business_name: string;
  description: string;
  location: string;
  department: string;
  latitude: number;
  longitude: number;
  is_verified: boolean;
  rating: number;
  review_count: number;
  years_experience: number;
  image_url: string;
  cover_url: string;
  categories: string[];
  phone: string;
  email: string;
}

export const seedProviders: SeedProvider[] = [
  {
    id: "prov-1",
    profile_id: "user-prov-1",
    business_name: "Eventos Elegantes GT",
    description: "Más de 15 años organizando eventos inolvidables en Ciudad de Guatemala. Especialistas en sillas Tiffany y mesas decorativas.",
    location: "Zona 10, Ciudad de Guatemala",
    department: "Guatemala",
    latitude: 14.6349,
    longitude: -90.5069,
    is_verified: true,
    rating: 4.8,
    review_count: 127,
    years_experience: 15,
    image_url: "/images/avatar1.jpg",
    cover_url: "/images/cover.jpg",
    categories: ["sillas-y-mesas", "decoracion"],
    phone: "+502 5555-0101",
    email: "contacto@eventoselegantesgt.com",
  },
  {
    id: "prov-2",
    profile_id: "user-prov-2",
    business_name: "Brinca Brinca Inflables",
    description: "Los mejores inflables de Guatemala. Desde castillos pequeños hasta mega resbaladeras acuáticas. Seguro, limpio y divertido.",
    location: "Mixco, Guatemala",
    department: "Guatemala",
    latitude: 14.6432,
    longitude: -90.5959,
    is_verified: true,
    rating: 4.9,
    review_count: 234,
    years_experience: 8,
    image_url: "/images/avatar2.jpg",
    cover_url: "/images/inflable.jpg",
    categories: ["inflables"],
    phone: "+502 5555-0202",
    email: "info@brincabrinca.gt",
  },
  {
    id: "prov-3",
    profile_id: "user-prov-3",
    business_name: "DJ Carlos M. - Sonido Profesional",
    description: "DJ con más de 10 años de experiencia en bodas, quinceañeras y eventos corporativos. Equipos JBL y Pioneer.",
    location: "Zona 14, Ciudad de Guatemala",
    department: "Guatemala",
    latitude: 14.585,
    longitude: -90.4905,
    is_verified: true,
    rating: 4.7,
    review_count: 89,
    years_experience: 10,
    image_url: "/images/avatar3.jpg",
    cover_url: "/images/dj.jpg",
    categories: ["sonido-e-iluminacion"],
    phone: "+502 5555-0303",
    email: "djcarlos@sonidopro.gt",
  },
  {
    id: "prov-4",
    profile_id: "user-prov-4",
    business_name: "Carpas del Altiplano",
    description: "Carpas elegantes para cualquier clima. Servicio en todo el altiplano guatemalteco: Quetzaltenango, Huehuetenango, Quiché.",
    location: "Quetzaltenango",
    department: "Quetzaltenango",
    latitude: 14.8529,
    longitude: -91.5326,
    is_verified: true,
    rating: 4.6,
    review_count: 45,
    years_experience: 12,
    image_url: "/images/avatar4.jpg",
    cover_url: "/images/mesa.jpg",
    categories: ["carpas-y-toldos"],
    phone: "+502 5555-0404",
    email: "info@carpasaltiplano.com",
  },
  {
    id: "prov-5",
    profile_id: "user-prov-5",
    business_name: "Banquetes Doña María",
    description: "Comida guatemalteca auténtica para eventos. Kaq ik, pepián, tamales y más. Servicio completo con meseros.",
    location: "Antigua Guatemala, Sacatepéquez",
    department: "Sacatepéquez",
    latitude: 14.5573,
    longitude: -90.7332,
    is_verified: true,
    rating: 4.9,
    review_count: 156,
    years_experience: 20,
    image_url: "/images/avatar5.jpg",
    cover_url: "/images/catering.jpg",
    categories: ["catering"],
    phone: "+502 5555-0505",
    email: "donamaria@banquetes.gt",
  },
  {
    id: "prov-6",
    profile_id: "user-prov-6",
    business_name: "Decorarte Quiché",
    description: "Decoración única con toques maya. Arcos de globos, flores nativas y textiles tradicionales. Directo de Santa Cruz del Quiché.",
    location: "Santa Cruz del Quiché",
    department: "Quiché",
    latitude: 15.0305,
    longitude: -91.1487,
    is_verified: true,
    rating: 4.8,
    review_count: 34,
    years_experience: 6,
    image_url: "/images/avatar6.jpg",
    cover_url: "/images/decoracion.jpg",
    categories: ["decoracion"],
    phone: "+502 5555-0606",
    email: "decorarte@quiche.gt",
  },
  {
    id: "prov-7",
    profile_id: "user-prov-7",
    business_name: "FotoMaya Estudio",
    description: "Fotografía profesional con visión maya. Bodas, quinceañeras, eventos corporativos y sesiones temáticas.",
    location: "Zona 1, Ciudad de Guatemala",
    department: "Guatemala",
    latitude: 14.6419,
    longitude: -90.5133,
    is_verified: true,
    rating: 4.7,
    review_count: 67,
    years_experience: 9,
    image_url: "/images/avatar7.jpg",
    cover_url: "/images/foto.jpg",
    categories: ["fotografia-y-video"],
    phone: "+502 5555-0707",
    email: "hola@fotomaya.gt",
  },
  {
    id: "prov-8",
    profile_id: "user-prov-8",
    business_name: "Vajillas de Lujo Xela",
    description: "Vajillas de cristal, porcelana y acero inoxidable. Servicio de meseros incluido. Disponible en Quetzaltenango y alrededores.",
    location: "Quetzaltenango",
    department: "Quetzaltenango",
    latitude: 14.8353,
    longitude: -91.5187,
    is_verified: true,
    rating: 4.5,
    review_count: 28,
    years_experience: 7,
    image_url: "/images/avatar8.jpg",
    cover_url: "/images/vajilla.jpg",
    categories: ["utensilios"],
    phone: "+502 5555-0808",
    email: "rentas@vajillasxela.com",
  },
  {
    id: "prov-9",
    profile_id: "user-prov-9",
    business_name: "Mega Sonido Huehue",
    description: "Sonido potente para eventos grandes y pequeños en Huehuetenango. Karaoke, luces LED y pantalla gigante.",
    location: "Huehuetenango",
    department: "Huehuetenango",
    latitude: 15.3193,
    longitude: -91.4724,
    is_verified: false,
    rating: 4.4,
    review_count: 19,
    years_experience: 4,
    image_url: "/images/avatar9.jpg",
    cover_url: "/images/dj.jpg",
    categories: ["sonido-e-iluminacion"],
    phone: "+502 5555-0909",
    email: "megasonido@huehue.gt",
  },
  {
    id: "prov-10",
    profile_id: "user-prov-10",
    business_name: "Catering Petén Selva",
    description: "Catering con ingredientes de la selva petenera. Exótico, fresco y delicioso. Ideal para eventos eco-turísticos.",
    location: "Flores, Petén",
    department: "Petén",
    latitude: 16.9234,
    longitude: -89.8867,
    is_verified: true,
    rating: 4.6,
    review_count: 22,
    years_experience: 5,
    image_url: "/images/avatar10.jpg",
    cover_url: "/images/catering.jpg",
    categories: ["catering"],
    phone: "+502 5555-1010",
    email: "selva@cateringpeten.com",
  },
];
